[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.import"
version = "4.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["imports", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.import"

[build-options]
observabilityIncluded = true
